/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ZipArchive {
  static fromBuffer(buffer: Buffer): ZipArchive
  isEmpty(): boolean
  readFile(name: string): Buffer
  readFileAsync(name: string, signal?: AbortSignal | undefined | null): Promise<Buffer>
  extract(outdir: string): void
  extractAsync(outdir: string, signal?: AbortSignal | undefined | null): Promise<void>
  fileNames(): Array<string>
}

export declare class ZipWriter {
  constructor()
  writeFile(filepath: string, realpath?: string | undefined | null, options?: WriteFileOptions | undefined | null): void
  finish(dst: string): void
  finishToBuffer(): Buffer
}

export type CompressionMethod =  'stored'|
'deflated'|
'deflate64'|
'bzip2'|
'aes'|
'zstd'|
'lzma'|
'xz';

export declare function openZipArchive(path: string): ZipArchive

export declare function openZipArchiveAsync(path: string, signal?: AbortSignal | undefined | null): Promise<ZipArchive>

export interface WriteFileOptions {
  compressionMethod?: CompressionMethod
  compressionLevel?: number
  permissions?: number
  largeFile?: boolean
}

export declare function writeZip(srcDir: string, dst: string, options?: WriteFileOptions | undefined | null): void

export declare function writeZipAsync(srcDir: string, dst: string, options?: WriteFileOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<void>
